# Generated by Django 4.0.6 on 2022-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='role',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
